Implements debug feature as described in #2
sindresorhus/emittery pull request #53
Opened 2020-03-25 20:34 UTC by sbencoding

This PR aims to implement a built-in debug feature described in #2
#### How it's implemented
There's a static function in the `Emittery` class called `debugLogger`, that takes in 4 parameters
* type - type of debug log
* debugName - set by the instance of Emittery that generated this log
* eventName - event name related to the log
* eventData - in case of emit, this is the data sent by it

Debugging can be triggered in 3 ways currently:
1. the `DEBUG` environment variable is set to *emittery* or *
2. the static `isDebug` function in Emittery returns true (by default this handles the environment variable, but this function can be overridden, to enable package wide debugging instead of the 3rd method.
3. the `isDebug` variable is set to true on one or more instances.
#### Questions/suggestions
I wasn't sure if the default logger function should include some sort of timestamp.

It might add too much complexity but a verbosity option could be nice. For example currently every emit, subscribe, unsubscribe etc. event is logged, but in some cases they might not all be interesting. Of course this can be achieved by overriding the `debugLogger` function on `Emittery`, but it would be a nice convenience option.

Is it acceptable that there's one static logging function on `Emittery` or should the individual instanced of it be able to override this function. This would add the ability for different instances of `Emittery` to log differently based on their function in an application.

2020-03-25 21:04 UTC, sbencoding commented
Not sure why codecov doesn't pickup that I test the `debugLogger` static function on `Emittery`.
Unfortunately I'm not familiar with this software, but I tried calling the method directly from one of the test cases and it still showed that I missed that function :(

2020-08-10 19:55 UTC, sindresorhus commented on index.js
> +	static isDebug() {
This should be a getter.

2020-08-10 19:56 UTC, sindresorhus commented on index.js
> +			eventName = eventName.toString();
This is moot. Template interpolation already calls toString.

2020-08-10 19:59 UTC, sindresorhus commented
> Questions/suggestions

Share your opinion on these questions.

2020-08-11 15:24 UTC, sbencoding commented
I've implemented the requested changes, updated documentation and tests where it was needed.
My thoughts on the questions:
#### Timestamps
I think it would be useful only in specific scenarios if the default logging function printed out timestamps as well. The use case I can currently think of where time is relevant is an application where an emit happens periodically e.g. every 10 seconds. I think a `minutes:seconds:milliseconds` format would be the best in this case, since I don't expect the debug to run for hours or days.
Because I can't think of better/more use cases I don't think this would be useful to have it in by default.
#### Verbosity filter
I think this is useful because with multiple events and multiple instances of Emittery the logs could get cluttered very quickly if we log every subscribe/unsubscribe event too. I can think of two approaches that would be good here.
1. Verbosity levels from 1 to 3
Where 1 only logs emits, 2 logs emits and sub/unsub, and 3 logs everything
2. An array of strings that defines the event types we're interested in
For example we could add emit, subscribe and clear to it, if those are the events we're interested in. This allows for more precise control than option number 1 but also takes a bit more time to set up.

The other thing that needs to be decided here is where we implement the verbosity setting, in the Emittery class, so it affects all instances at once, or on a per instance level, so it's more precisely controllable. However on the per instance level we would have to manually update every instance if we wanted to change the setting for all instances.
Overall I would say that implementing it globally is better because it would be more efficient at reducing the overall clutter.

#### Static logger function
I think it would be better to have this on a per instance basis, but I guess this question is kind of the same as the implementation of the verbosity filter. The benefit of logging on a per instance basis would be that the different instances could access potentially useful data that is only available in their context. But again the drawback is that we lose the ability to update the logging function of all instances all at once.
Overall I think implementing this on a per instance basis would provide more functionality than it would take away. I couldn't come up with a use case where updating every logger function would be that important, but I can imagine that some instances would like to log information only available in their context.

2021-03-07 10:38 UTC, sindresorhus commented
Sorry, I just realized I missed the notification for this.

2021-03-07 10:38 UTC, sindresorhus commented
> Timestamps

I think timestamp can be useful for comparing how far from eachother certain events are. I agree, the date is not very useful, but it should follow the ISO9601 minus the date, so `hours:minutes:seconds.milliseconds`. I think timestamps should be on by default. We can add an option to remove based on future requests.

> Verbosity filter

I'm not sold on this. I think it's better to just be verbose by default and we can add modes to make it less verbose when users requests it from real-world experience.

> Static logger function

Yeah, it should be on the instance.


---

I think it should be `{debug: {name: 'foo'}}`, not `{debugName: 'foo'}`. The former lets us add more debug-related options later on.

---

The docs and TS docs comments needs more work regarding formatting and typos.

2021-03-20 16:39 UTC, sbencoding commented
Here are some of the changes I've made:
* `name` for debugging is passed as part of an object that contains debugging setup data in the constructor
* `debugLogger` is no longer static, instead `logger` is set in the debug options
* `isDebug` that was on the instance is now set in debug options as well. The global `isDebug` that controls debugging for all instances is kept as it was before
* Add timestamp to the default logger function
* Update tests
* Update documentation (both readme and typescript)

Let me know if I've missed anything, or there's something that could be done in a better way

P.S. finally I pass all the checks yay!

2021-05-19 07:58 UTC, sindresorhus requested changes

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +See API for more information on how debugging works
All sentences should end with a `.`

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +type DebugLogger = (type: string, debugName: string, eventName?: EventName, eventData?: Record<string, any>) => void;
The event data here should be strongly-typed.

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +	//	data: undefined
This is too cramped. Use more empty lines to make it more readable. The example should also include the part that emits the event. Generally, code examples should be runnable on their own.

Applies to all code examples.

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +	@default Empty string
This is not a valid value for `@default`.

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +	name: string;
```suggestion
	readonly name: string;
```

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +	Enable/Disable debug logging just for this instance
```suggestion
	Toggle debug logging just for this instance.
```

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +	@example
```suggestion

	@example
```

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +			eventData = JSON.stringify(eventData);
I think it's easier to just always stringily the value.

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +		}
This is moot. Template string interpolation already handles this.

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +Configure a new instance of Emittery
Incorrect description.

2021-05-19 07:58 UTC, sindresorhus commented on index.d.ts
> +	*/
This `@default` block here is not needed. It's already document on the individual options.

2021-05-19 07:58 UTC, sindresorhus commented on index.js
> +let globalDebugFlag = false;
```suggestion
let isGlobalDebugEnabled = false;
```

2021-05-19 07:58 UTC, sindresorhus commented on index.js
> +	static get isDebug() {
```suggestion
	static get isDebugEnabled() {
```

Just to make it clear.

2021-05-19 07:58 UTC, sindresorhus commented on index.js
> +		}
I don't get what the point of this is.

2021-05-19 07:58 UTC, sindresorhus commented on index.js
> +			}
This is repeated many times. There should be a utility method for this.

2021-05-19 07:58 UTC, sindresorhus commented on readme.md
> +Enables/Disables debug mode for all instances
```suggestion
### isDebug

Toggle debug mode for all instances.
```

Formatting

2021-05-19 07:58 UTC, sindresorhus commented
The code looks good, but the docs formatting and text needs more work.

2021-05-23 11:09 UTC, sbencoding commented
I implemented the requested changes
1. I wasn't sure how to make `DebugLogger` in `index.d.ts` strongly-typed properly, but I've tried, please let me know if there's a better way to do this, or if how I did it is correct at all.
2. I couldn't remove the following code
```js
if (typeof eventName === 'symbol') {
        eventName = eventName.toString();
}
```
Because it throws `TypeError: Cannot convert a Symbol value to a string` when the string interpolation happens.
I've tried a small, isolated example:
```js
let s = Symbol('test');
console.log(`Symbol to string: ${s}`);
```
This results in the same error, so I don't know if there's a way to work around this.

2021-05-25 13:11 UTC, sindresorhus commented on readme.md
> +Default: `null`
I prefer using `undefined` over `null`.

2021-05-25 13:13 UTC, sindresorhus commented on readme.md
> +emitter.emit('test');
Readme and index.d.ts should be in sync.

2021-05-25 13:14 UTC, sindresorhus commented
> I wasn't sure how to make DebugLogger in index.d.ts strongly-typed properly, but I've tried, please let me know if there's a better way to do this, or if how I did it is correct at all.

I would recommend writing some type tests to confirm it's correct: https://github.com/sindresorhus/emittery/blob/main/index.test-d.ts

> I couldn't remove the following code

Ah yeah. I forgot it's not interpolatable.

2021-05-27 10:01 UTC, sbencoding commented
I've implemented the changes, and wrote some type tests for the strongly-typed logger

2021-05-28 14:14 UTC, merged